apiversion: v1
kind: Service
metadata: 
  name: gohelloworld
  spec: 
    selector:
      app: gohelloworld
      ports:
        name: http
        protocol: TCP
        port: 80
        targetPort: 8080