apiVersion: apps/v1
kind: Deployment
metadata:
  name: jump
  labels:
    k8s-app: jump
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: jump
  template:
    metadata:
      name: jump
      labels:
        k8s-app: jump
    spec:
      containers:
        - name: jump
          image: ubuntu:latest
          tty: true
          stdin: true