# This ConfigMap is just a way to define the cloudflared config.yaml file in k8s.
# It's useful to define it in k8s, rather than as a stand-alone .yaml file, because
# this lets you use various k8s templating solutions (e.g. Helm charts) to
# parameterize your config, instead of just using string literals.
apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudflared
data:
  config.yaml: |
    tunnel: ana-pi-cluster
    credentials-file: /etc/cloudflared/creds/3d880b14-b44c-4a24-9ae5-49c5098d6253.json
    metrics: 0.0.0.0:2000
    no-autoupdate: true
    ingress:
    - hostname: helloworld-v2.gawn.dev
      service: http://helloworld.default.svc.cluster.local
    - hostname: kube-dash-v2.gawn.dev
      service: https://kubernetes-dashboard.default.svc.cluster.local
    - hostname: argocd-v2.gawn.dev
      service: https://argocd-server.default.svc.cluster.local
    - service: http_status:404