apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: cloudflared
  namespace: cloudflared

resources:
  - deployment.yaml
  - config.yaml
  - cloudflared-tunnel-creds.yaml
  - namespace.yaml