apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: betterstack
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: >-
      https://helm.datadoghq.com
    targetRevision: 1.3.0
    chart: betterstack
    helm:
      valuesObject:
        vector:
          customConfig:
            sinks:
              better_stack_http_sink:
                auth:
                  token: $token
              better_stack_http_metrics_sink:
                auth:
                  token: $token
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: betterstack
  