---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ghcr-secret
  namespace: argocd
spec:
  encryptedData:
    .dockerconfigjson: AgAqNjYVZHTFpplKPXOxvEm6YfaLLeOEKtpVRbBEXjOjUuZBeq+6ACnf5JdUme+vxM3MZ3b/DayPtUVwcu7Gv0TJ/8h5MumC2kk5OlM6lTHleMAJY51KxuGYor5Ujar35vKp+1crmA+eLIj4AuaghP+a5YswFANqhcb6oWKDXFX0XBuMncrGIx01nY0u4YR9WPAkk59dS/3tG+wZ9OMJWohk8numqupTtYKkHisYqa6nBpj4k598wyCP5NRVC3GYPgTFQxvWNkz1Rb9KWVhhmK23rCF/Z1ARN8IJEPV53xdprmgHxy/0AKZDRvaI1QPTivy53JHjqvyZlbebv9cKdIb/hZlE5o/Y7h8RSyWt/oPEO7rKk2nSnquXh6ypTT1D4NCTLFcysMHIFu1B0BelKaROnAL3RpGvTgaA+e2baXKCNiqpPTb+FlRHq8J3YoS39lhg8Hywt8g1dPOhyPjkADlzVthHsgblRat5gfMX/mMuESN4mRfRKJPZc1p32bY47DMfgqLlmHsj1x5ILvuOHTFRTfrobUstTL22pZko/IwG2eVBvMPKniXeaMtN2ogIGIWS3ps9M1jOjxSt1aNPzMY5eJBNms0lUVFQbeTsD7DnhSMVv+Nzv++mtwQFW0YVK9VkhXuAM1xWAvKvtJlH53+9eoZWVQ0/hZlqimbAwxttS5mafKX8jnt2BrNQPYGDc3aGmXaaRRY2rZxzx/D/tk5zRfQTlfkvtnIYFV8F+J/ezyVzck6/rrXYEdXQ8KNbxihTEPOre5jci/wqPjIkNshX2ipPk0Cx4tHekSekQIgiX8/16qS0lRDJnsq6V5qUGR7a0v97p2PWVlf2u86LbQhrd6cRi4MEeDs2GXAl4CoOeRtOEBE0yFMsHwMhxqZvWKJkf2Sc/2sQ3gIca9XaGilpMw2zSAfcZswo9LMGh2lnF7G7GZvRgahngZI=
  template:
    metadata:
      creationTimestamp: null
      name: ghcr-secret
      namespace: argocd
    type: kubernetes.io/dockerconfigjson