apiVersion: batch/v1
kind: CronJob
metadata:
  name: ng-dfs-notifier
spec:
  schedule: "5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: ng-dfs-notifier
            image: ghcr.io/jamesgawn/ng-dfs-notifier
            imagePullPolicy: IfNotPresent
            command:
            - /ng-dfs-notifier
            volumeMounts:
            - name: nfs
              mountPath: "/storage"
              readOnly: false
            env:
            - name: TELEGRAM_BOT_TOKEN
              valueFrom: 
                secretKeyRef:
                  name: telegam-bot-secret
                  key: token
          volumes:
            - name: nfs
              persistentVolumeClaim:
                claimName: database-storage-pvc