apiVersion: batch/v1
kind: CronJob
metadata:
  name: ng-dfs-notifier
spec:
  schedule: "5 * * * *"
  jobTemplate:
    spec:
      suspend: false
      backoffLimit: 2
      template:
        spec:
          volumes:
            - name: nfs
              persistentVolumeClaim:
                claimName: database-storage-pvc
          containers:
          - name: ng-dfs-notifier
            image: ghcr.io/jamesgawn/ng-dfs-notifier:0.1.3
            imagePullPolicy: IfNotPresent
            command:
            - /ng-dfs-notifier
            args: ["databaseLocation", "/storage/events.db"]
            volumeMounts:
            - name: nfs
              mountPath: "/storage"
              readOnly: false
            env:
            - name: TELEGRAM_BOT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: telegam-bot-secret
                  key: token
          restartPolicy: Never