apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ng-dfs-notifier
metadata:
  name: ng-dfs-notifier

resources:
  - "storage.yaml"
  - "telegram-bot-secret.yaml"
  - "cronjob.yaml"