---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: telegam-bot-secret
  namespace: default
spec:
  encryptedData:
    token: AgBtfqSKydt0QZ2rllf0saoDIiGDzqohehmlNte2t85O1TAwUv27LctnPUpqm3v+Ksh/tGMn/oDFSHE82wxdSHOSLeFThG15/rFYFxiycqzNnP05GYobr9u47k4Q/gBlMkTdJMBBh8Tc0ZGNVRxN0Pzpo/5stZrSYy0ls+1DLuxKgCwGwE31OFHsReKu7xmalKEUTGJtlENkeXZPNiNbiNWZX0MQw26kTY6/6aw8fZl3QkKSgHZcug0iGY0AYxSpG95I2JabX6iNv/xDrfdPRzhQYCJsiHw+RcBf5SiqGKde/w9/c3E1jtqVw3CrjgV1exFq1GqKiL6uSm3GNhQXzVTb/OuOGrusCVbUaDW0cnjNF4PNeE4cmAP+YaNKdr4Ju6SS/c+q2YnlRkxSl3qt/IxR+yEXe6h93fEdZCQZzUU36muXIWb3gObWE56KQzIkl0xoVlWmWAnQVhgeDc3jm79wyfd7aOKcT5NrJc1Vh4TMEtGvohyyjJVFfcZ3nu67tcRLfTUKoyAvXy13ETGcZzYBa4coXEQIULtazP2/bwFumVhLeu3jahsk8m/8EqIliGolVsdSvYhQ0Vvfggs4GTafUphBToIJSgEAp1k8ABqtONGR5lDJ0SU3ZQBpke6iRT6rfCSmzi9HOQoLN3oru9IYm4QmaCbbQD2t9nvUwOOHQVQZIAqG8vqp8ltjm1bQRrUHflirNhXwzmhXYofP/lb8nBuXNb6RuTcVmbnLjXis5+imI+A1TMiFlcu/IHTa
  template:
    metadata:
      creationTimestamp: null
      name: telegam-bot-secret
      namespace: default
    type: string
