apiVersion: apps/v1
kind: Deployment
metadata:
  name: test
  namespace: ng-dfs-notifier
  labels:
    k8s-app: test
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: test
  template:
    metadata:
      name: test
      labels:
        k8s-app: test
    spec:
      containers:
        - name: test
          image: arm64v8/ubuntu:22.04
          securityContext:
            privileged: false
          volumeMounts:
            - name: nfs
              mountPath: "/mnt/storage"
              readOnly: false
      volumes:
        - name: nfs
          persistentVolumeClaim:
            claimName: database-storage-pvc