apiVersion: apps/v1
kind: Deployment
metadata:
  name: jump
  namespace: ng-dfs-notifier
  labels:
    k8s-app: jump
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: jump
  template:
    metadata:
      name: jump
      labels:
        k8s-app: jump
    spec:
      containers:
        - name: jump
          image: ubuntu:latest
          tty: true
          stdin: true
          volumeMounts:
            - name: nfs
              mountPath: "/mnt"
              readOnly: false
      volumes:
        - name: nfs
          persistentVolumeClaim:
            claimName: database-storage-pvc