apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: betterstack
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: betterstack
    server: 'https://kubernetes.default.svc'
  source:
    path: system/betterstack
    repoURL: 'git@github.com:jamesgawn/k8s-home.git'
    targetRevision: HEAD
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: false