apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: reloader
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://stakater.github.io/stakater-charts
    targetRevision: 1.0.56
    chart: stakater/reloader
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: reloader