---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-test1
spec:
  accessModes:
    - ReadWriteMany  # In this example, multiple Pods consume the same PVC.
  resources:
    requests:
      storage: 10Gi
  storageClassName: handside-nas-nfs