apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helloworld
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: default
    server: 'https://kubernetes.default.svc'
  source:
    path: apps/helloworld
    repoURL: 'git@github.com:jamesgawn/k8s-home.git'
    targetRevision: HEAD
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true