apiVersion: v1
kind: Service
metadata:
  name: ingress
  namespace: ingress
  labels:
    app.kubernetes.io/name: ingress
    app.kubernetes.io/part-of: ingress
spec:
  type: NodePort
  externalIPs:
    - "192.168.20.171"
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080
    - name: https
      protocol: TCP
      port: 433
      targetPort: 443
      nodePort: 30443
  selector:
    app.kubernetes.io/name: ingress
    app.kubernetes.io/part-of: ingress