kind: DatadogAgent
apiVersion: datadoghq.com/v2alpha1
metadata:
  name: datadog
  namespace: datadog
spec:
  global:
    site: datadoghq.eu
    credentials:
      apiSecret:
        secretName: datadog-secret
        keyName: api-key
      appSecret:
        secretName: datadog-secret
        keyName: app-key
  features:
    liveContainerCollection:
      enabled: true
  override:
    clusterAgent:
      image:
        name: gcr.io/datadoghq/cluster-agent:latest
      env: 
        - name: DD_CLUSTER_NAME
          value: "k8s-home"
    nodeAgent:
      image:
        name: gcr.io/datadoghq/agent:latest