---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: datadog-secret
  namespace: datadog
spec:
  encryptedData:
    api-key: AgCU5kXj8hSL12KW5PoBPl6fUgX7fWIWNOK1vInLietbyUxciGr0WDhsJSB4K1p0vz4XLHr7l2Di4NwJUX1gleWHq1TdRKSIfk6ZnnlN/Q+IP0qWBGhzUvNvCQZYaOMQGqsnaKQEZOU6Ja+xH5biep3apKmG5N6cA5Nsi7Rbl45YG5vVhKcfXYvyWXEIN/lq8ERsWyfKirRThFZdmrKGzrHvZSKp9p3FWtYGc5TGWYBDYVWjgUf1f/Lj8DGFORtm3GVg2mVZHKTNnQfWJYSGSjZlRkvQERxzkjAjZDYE0JZ76BxdJ/qsAqNSTxeCJbvJoyX4eaUwxvJmI7FoVUCJGnlC8Kbs/W5Zc9DoOUtAaMS2Pm5hL26sgHY079dyiS7ADxOLLuazrRNLCR6s3SVDpzkwg0BIAFBGio9KdLPXgiicXS6HOx8WWxL8udTyM+68D8EWIL3j801unv4XsScQ7tV0gOaF63zMntorjl4JUVv/bNDJtKhFDy14KF+rjMboLkcR0OrORW6wvqWhhbaVucZTa8vOAF/t7tLVARjCbolRD6eNfRhPPGs4OFrqH5BySt0B1BHatjB9Xa62Co+/wtyDRWVS/spbimWbSmcERY/s2UsDe7viZeEqgP58X15CS2hamx5zNd/hBR1DUnwnOKIA3rScI6M1+J8oGda8zBe6efHEylIDnuTSTzwXFPAaF3ID6D8lm7oyGAaMzIVPebQERJfKGWsc7pt7JeggEPWgpoH0CXw=
    app-key: AgCsp8wd4escDBrBfc2GnRauemVs/Dv8ifGyZBCSsB5elvSPmQZmfbus0UbKQ4LbVzKG47x22RI0nYdXAL2RuudKVbrkhpZAHXQraT3SNsRmaqkfczosh2lKOkIPtgr4XZ1EZiM57PSiB8IWl/gzQJTDWyHS/n7a/Gfze0rxA/L+yaWF9bkZXi6X8ooHJee2FnA1Z/Eg5q6F+7kklnqsuVOzKcasW9kVAE+sSKI7KCReGHLZZOSVEdCaYFVCJVGbHiw8UY2Guo8IhCMxJkdr1HK/fktfMJR821QlSS0SabdYZ1Ew3VGvSVYf5i1920dckrPppas8/Y3Ap6qczLONVbpfHV6gm8sKz8LnIZMM4vDwQ9B1M84QeHJ7mJokxf43q7HXeAwZm7cG6ydMt39j7EHNlpc7NeRRN3iZxPjl9A5jlmpOHWk/wgN4WHsfeNHPmpwXdWvwEwFZ4lofiPN4SnKHe5i5fw/awqgyM0SHtP/F+J8zDdUgKhJJYuhnusZyl819HTBcYUEtx6dfM3DQx4OzqkVGtt9iVUG+QUNlMaXBJUWqwrAz6HQRS72/EGagO4xnIevpXPaEgnM+XmIu0b4FgfTZ/q3s20fO3vcxzoQ/ebDm2y9zg1RCf7M8/Vf17zGQngS++a9BJP8r28kFbAWoSX7KlZ+lnSmY7D1Y6kNxztRxd2k1iIr67/QKxXnDxPAo0JGwQM+uKN72+BuUWxZ4rbKTgK59//CStQjPAfbolJU9fGO9Sk9i
  template:
    metadata:
      creationTimestamp: null
      name: datadog-secret
      namespace: default